#
# pilha : negritando-ecs-api
# - diagrama
# client
# 	security group 1 (filtro = in, tcp, 80, *ip)
# 		load balance
# 			security group (filtro = in, tcp, 80, security group 1)
# 				task/servico/container
# - dependencias
#   arn:aws:iam::{conta}:policy/cmj-parameters-dev


AWSTemplateFormatVersion: 2010-09-09
Description: Template que cria uma instancia ecs/fargate. Autor Fernando Rodrigues
Parameters:
  CMJServiceName:
    Type: String
    Default: negritandoApi  
  CMJServiceName1:
    Type: String
    Default: negritandoApi1  
  CMJServiceImage:
    Type: String
    Default: nandolrs/cftstapi-image    
  CMJVpcId:
    Type: AWS::EC2::VPC::Id
  CMJContainerPort:
    Type: Number
    Default: 80
  CMJListenerPort:
    Type: Number
    Default: 80    #original = 443 se usar o certificado, 80 se nao usar o certificado     
  CMJTargetGroupHealthCheckPath:
    Type: String
    Default: /api
    # caminho do health do servico
  CMJEnviromentName:
    Type: String
    Default: treinamento
    AllowedValues:
    - dev
    - hom
    - prd
    - treinamento
    # nome do ambiente: dev/hom/prd/...    
  CMJLogGroupName:
    Type: String
    Default: /ecs/api-front
    # caminho do log do cloud whatch      
  CMJCertificateUsageQuestion:
    Type: String
    Default: no
    AllowedValues :
      - yes
      - no    
    Description : Are you to use a SSL/TSL certificate?
    # to question if a certificate will be use
  CMJCertificateArn:
    Type: String
    Default: arn:aws:acm:<REGIAO>:<CONTA>:certificate/<CERTIFICADO>
    Description : Informar o ARN SSL/TSL do certificado
    # update with the ARN of certificate
  CMJScalableTargetMinCapacity:
    Type: Number
    Default: 2
    Description : Informar a quantidade minima de instancias
    # input the instances minimum quantity   ScalableTarget.MinCapacity
  CMJScalableTargetMaxCapacity:
    Type: Number
    Default: 6
    Description : Informar a quantidade maxima de instancias
    # input the instances maximum quantity   ScalableTarget.MaxCapacity
  CMJScalingPolicyTargetValue:
      Type: Number
      Default: 3  
      Description : Informar percentual maximo de CPU antes de escalar
      # input the max percent CPU before auto scaling   TargetTrackingScalingPolicyConfiguration.TargetValue
  CMJDBName:
    Default: dbcftreino
    Description: Nome da base de dados
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Deve comecar com uma letra e conter somente coracteres alfanumericos.
Conditions:
  CMJCertificateUsageQuestionCondition: !Equals
    - !Ref CMJCertificateUsageQuestion
    - yes
  CMJCertificateUsageQuestionNoCondition: !Equals
    - !Ref CMJCertificateUsageQuestion
    - no
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Rede e ambiente
        Parameters: 
          - CMJVpcId
      - 
        Label: 
          default: "Aplicacao"
        Parameters: 
          - CMJEnviromentName
          - CMJDBName
          - CMJLogGroupName
      - 
        Label: 
          default: "Container"
        Parameters: 
          - CMJServiceImage
          - CMJContainerPort
          - CMJServiceName
          - CMJServiceName1   
      - 
        Label: 
          default: "Load balance/auto scaling"
        Parameters: 
          - CMJListenerPort
          - CMJTargetGroupHealthCheckPath
          - CMJScalableTargetMinCapacity
          - CMJScalingPolicyTargetValue      
          - CMJScalableTargetMaxCapacity
      - 
        Label: 
          default: "Rota"
        Parameters: 
          - CMJCertificateUsageQuestion
          - CMJCertificateArn                         
    ParameterLabels: 
      CMJVpcId: 
        default: "Nome da rede"   

      CMJEnviromentName: 
        default: "Ambiente"

      CMJLogGroupName: 
        default: "Caminho/nome do log"

      CMJDBName: 
        default: "Nome da base de dados"
        
      CMJContainerPort: 
        default: "Porta"   

      CMJServiceName: 
        default: "Nome do servico"           


      CMJServiceName1: 
        default: "Nome do servico-1"           

      CMJServiceCMJServiceImageName1: 
        default: "Caminho/nome da imagem"   

      CMJListenerPort: 
        default: "Porta"          

      CMJTargetGroupHealthCheckPath: 
        default: "Caminho para determinar saude"    

      CMJScalableTargetMinCapacity: 
        default: "Quantidade minima de instancias"   

      CMJScalingPolicyTargetValue: 
        default: "Quantidade desejavel"   

      CMJScalableTargetMaxCapacity: 
        default: "Quantidade maxima de instancias"    

      CMJCertificateUsageQuestion: 
        default: "Usar certificados?"   

      CMJCertificateArn: 
        default: "Caminho do certificado" 
Resources:
  CMJECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: cmj
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
  CMJECSIamRoleEcsTasks:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cmjIAMRole-ecs-tasks
      AssumeRolePolicyDocument:
        Statement:
            - Action: 'sts:AssumeRole'
              Principal:
                Service: ecs-tasks.amazonaws.com
              Effect: Allow
            - Action: 'sts:AssumeRole'
              Principal:
                Service: ssm.amazonaws.com
              Effect: Allow
      Policies:
        - PolicyName: cmjIAMPolicy-ssm-parameter
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'ssm:GetParameter'
                Resource: !Sub  'arn:aws:ssm:*:${AWS::AccountId}:parameter/*'   
                Effect: Allow
  CMJECSIamRoleEcsTasksExecution:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cmjIAMRole-ecs-tasks-execution
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  CMJLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref CMJLogGroupName
  CMJContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref CMJServiceName, CMJContainerSecurityGroup]]
      VpcId: !Ref CMJVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref CMJContainerPort
          ToPort: !Ref CMJContainerPort
          SourceSecurityGroupId: !Ref CMJLoadBalancerSecurityGroup      
  CMJLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref CMJServiceName, CMJLoadBalancerSecurityGroup]]
      VpcId: !Ref CMJVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref CMJListenerPort
          ToPort: !Ref CMJListenerPort
          CidrIp: 0.0.0.0/0      
  CMJLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        # este e o padrao, porem especifique aqui se precisar mudar
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Name: !Join ['', [!Ref CMJServiceName, LoadBalancer]]
      # "internal" tambem e uma opcao
      Scheme: internet-facing
      SecurityGroups:
        - !Ref CMJLoadBalancerSecurityGroup
      Subnets:
            - subnet-ecbaf9b7
            - subnet-561f5b30
            - subnet-06106a4f
  CMJTargetGroupHTTP:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      # espera pelo codigo de status  200 por padrao, a menos que especifique outro
      HealthCheckPath: !Ref CMJTargetGroupHealthCheckPath
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['', [!Ref CMJServiceName, TargetGroup]]
      Port: !Ref CMJContainerPort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # padrao e 300
      TargetType: ip
      VpcId: !Ref CMJVpcId
  CMJTargetGroupHTTP1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      # espera pelo codigo de status  200 por padrao, a menos que especifique outro
      HealthCheckPath: !Ref CMJTargetGroupHealthCheckPath
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['', [!Ref CMJServiceName, TargetGroup,'1']]
      Port: !Ref CMJContainerPort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # padrao e 300
      TargetType: ip
      VpcId: !Ref CMJVpcId        
  CMJListenerHTTP:
    Condition:  CMJCertificateUsageQuestionNoCondition
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref CMJTargetGroupHTTP # ouve HTTPS, mas entrega HTTP para o servico
          Type: forward
      LoadBalancerArn: !Ref CMJLoadBalancer
      Port: !Ref CMJListenerPort
      Protocol: HTTP
  ListenerRuleHTTP:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - ForwardConfig: 
            TargetGroups: 
              - TargetGroupArn: !Ref CMJTargetGroupHTTP
                #Weight: Integer
          Type: forward 
      Conditions: 
        - Field : query-string
          QueryStringConfig : 
            Values: 
              - Key: caminho
                Value: 1
      ListenerArn: !Ref CMJListenerHTTP
      Priority: 1      
  ListenerRuleHTTP1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - ForwardConfig: 
            TargetGroups: 
              - TargetGroupArn: !Ref CMJTargetGroupHTTP1
                #Weight: Integer
          Type: forward 
      Conditions: 
        - Field : query-string
          QueryStringConfig : 
            Values: 
              - Key: caminho
                Value: 2
      ListenerArn: !Ref CMJListenerHTTP
      Priority: 2      
  CMJECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Memory: 512 #4096
      Cpu: 256 #512 
      ExecutionRoleArn: !Ref CMJECSIamRoleEcsTasksExecution
      TaskRoleArn : !Ref CMJECSIamRoleEcsTasks
      ContainerDefinitions:
        - Name:  !Ref CMJServiceName
          Image: !Ref CMJServiceImage
          PortMappings:
            - ContainerPort: !Ref CMJContainerPort
          # envia os logs ao CloudWatch 
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref CMJLogGroup
              awslogs-stream-prefix: ecs
          Environment :
            - Name: CMJ_AMBIENTE
              Value : !Ref CMJEnviromentName
            - Name: CMJ_VERSAO
              Value : v1r-1UM    
            - Name: CMJ_BASE
              Value : !Ref CMJDBName                  
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0539f1a2-9de4-436a-b92b-5c965b0a443a
    DependsOn:
      - CMJECSCluster
  CMJECSTaskDefinition1:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Memory: 512 #4096
      Cpu: 256 #512 
      ExecutionRoleArn: !Ref CMJECSIamRoleEcsTasksExecution
      TaskRoleArn : !Ref CMJECSIamRoleEcsTasks
      ContainerDefinitions:
        - Name:  !Ref CMJServiceName1  
          Image: !Ref CMJServiceImage
          PortMappings:
            - ContainerPort: !Ref CMJContainerPort
          # envia os logs ao CloudWatch 
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref CMJLogGroup
              awslogs-stream-prefix: ecs
          Environment :
            - Name: CMJ_AMBIENTE
              Value : !Ref CMJEnviromentName
            - Name: CMJ_VERSAO
              Value : v1r-2DOIS     
            - Name: CMJ_BASE
              Value : !Ref CMJDBName                               
    DependsOn:
      - CMJECSCluster
  CMJECSServiceHTTP:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Ref CMJServiceName
      LaunchType : FARGATE
      TaskDefinition : !Ref CMJECSTaskDefinition
      Cluster : !Ref CMJECSCluster   
      DesiredCount : 2
      DeploymentConfiguration :
        MinimumHealthyPercent : 100
        MaximumPercent : 200
      NetworkConfiguration :
        AwsvpcConfiguration :
          SecurityGroups : 
            - !Ref CMJContainerSecurityGroup
          AssignPublicIp : ENABLED
          Subnets : 
            - subnet-ecbaf9b7
            - subnet-561f5b30
            - subnet-06106a4f
      LoadBalancers:
        - ContainerName: !Ref CMJServiceName # mesmo que ContainerDefinitions.Name
          ContainerPort: !Ref CMJContainerPort
          TargetGroupArn: !Ref CMJTargetGroupHTTP            
    DependsOn:
      - CMJECSCluster    
      - CMJListenerHTTP
      - CMJTargetGroupHTTP  
  CMJECSServiceHTTP1:       # <?> ta dando erro aqui aleatoriamente
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Ref CMJServiceName1 
      LaunchType : FARGATE
      TaskDefinition : !Ref CMJECSTaskDefinition1
      Cluster : !Ref CMJECSCluster   
      DesiredCount : 2
      DeploymentConfiguration :
        MinimumHealthyPercent : 100
        MaximumPercent : 200
      NetworkConfiguration :
        AwsvpcConfiguration :
          SecurityGroups : 
            - !Ref CMJContainerSecurityGroup
          AssignPublicIp : ENABLED
          Subnets : 
            - subnet-ecbaf9b7
            - subnet-561f5b30
            - subnet-06106a4f
      LoadBalancers:
        - ContainerName: !Ref CMJServiceName1 # mesmo que ContainerDefinitions.Name
          ContainerPort: !Ref CMJContainerPort
          TargetGroupArn: !Ref CMJTargetGroupHTTP1             
    DependsOn:
      - CMJECSCluster    
      - CMJListenerHTTP           
      - CMJTargetGroupHTTP1  
  CMJScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties: 
      MinCapacity: !Ref CMJScalableTargetMinCapacity
      MaxCapacity: !Ref CMJScalableTargetMaxCapacity
      ResourceId: !Join ['/', [service, !Ref CMJECSCluster, !Ref CMJServiceName ]] 
      RoleARN: 
        Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: 'ecs:service:DesiredCount' 
      ServiceNamespace: ecs 
    DependsOn:
      - CMJECSServiceHTTP
  CMJScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties: 
      PolicyName: !Join ['', [!Ref CMJServiceName, ScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref CMJScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        PredefinedMetricSpecification: 
            PredefinedMetricType: ECSServiceAverageCPUUtilization # ECSServiceAverageCPUUtilization/ECSServiceAverageMemoryUtilization/ ALBRequestCountPerTarget 
        TargetValue: !Ref CMJScalingPolicyTargetValue
Outputs:
  CMJECSClusterOutputs:
    Description: Cluster ecs/fargate
    Value: !Ref CMJECSCluster
    Export:
      Name: CMJECSClusterOut 
  CMJECSIamRoleEcsTasksOutputs:
    Description: IamRole task ecs/fargate
    Value: !Ref CMJECSIamRoleEcsTasks
    Export:
      Name: CMJECSIamRoleEcsTasksOut    
  CMJECSIamRoleEcsTasksExecutionOutputs:
    Description: IamRole tasks execution ecs/fargate
    Value: !Ref CMJECSIamRoleEcsTasksExecution
    Export:
      Name: CMJECSIamRoleEcsTasksExecutionOut          
  CMJLoadBalancerOutputs:
    Description: Load balance to use
    Value: !Ref CMJLoadBalancer
    Export:
      Name: CMJLoadBalancerOut 
  CMJContainerSecurityGroupOutputs:
    Description: Security group do ECS container
    Value: !Ref CMJContainerSecurityGroup
    Export:
      Name: CCMJContainerSecurityGroupOut       
  CMJLoadBalancerDNSNameOutputs:
    Description: Load balance endpoint
    Value: !GetAtt CMJLoadBalancer.DNSName 
    Export:
      Name:  !Join  ['', [!Ref CMJServiceName, LoadBalancer,'Out']]   


      