#
# pilha : negritando-rds-mysql
#
AWSTemplateFormatVersion: 2010-09-09
Description: Template que cria uma instancia mysql. Autor Fernando Rodrigues
Parameters:
  CMJDBInstanceIdentifier:
    Default: dbnegritando
    Description: Nome da instancia
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Precisa iniciar com letras e não deve terminar com um ou mais hifens    
  CMJDBName:
    Default: dbcftreino
    Description: Nome da base de dados
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Deve comecar com uma letra e conter somente coracteres alfanumericos.
  CMJDBInstanceClass:
    Default: db.t3.micro
    Description: Classe da instancia DB
    Type: String
    ConstraintDescription: Selecione um tipo valido de instancia DB.
  CMJAllocatedStorage:
    Default: '20'
    Description: Tamanho da base de dados (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: Deve estar entre 20 e 65536 GiB.
  CMJMasterUsername:
    Default: dandaraQuilombo
    Description: Nome do usuario para acessar a base de dados  MySQL.
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Deve comecar com uma letra e conter somente caracteres.
  CMJMasterUserPassword:
    NoEcho: 'true'
    Description: Senha de acesso da base de dados MySQL.
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Deve conter somente caracteres.
  CMJVpcId:
    Type: AWS::EC2::VPC::Id
  CMJCidrIpPermitido:
    Default: 0.0.0.0/32
    Description: Informe o IP da sua estacao de trabalho para que somente ela tenha acesso ao servico.
    Type: String
  CMJEnviromentName:
    Default: treinamento
    Type: String
    AllowedValues:
    - dev
    - hom
    - prd
    - treinamento
  CMJCriarParametrosPergunta:
    Default: sim
    Type: String
    AllowedValues:
    - sim
    - nao
  CMJAcessoPublicoPergunta:
    Default: sim
    Type: String
    AllowedValues:
    - sim
    - nao    
Conditions:
  CMJCriarParametrosCondicao: !Equals 
    - !Ref CMJCriarParametrosPergunta
    - sim    
  CMJAcessoPublicoCondicao: !Equals 
    - !Ref CMJAcessoPublicoPergunta
    - sim        
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Dados da rede e ambiente"
        Parameters: 
          - CMJCriarParametrosPergunta
          - CMJAcessoPublicoPergunta          
          - CMJEnviromentName
          - CMJVpcId
          - CMJCidrIpPermitido
      - 
        Label: 
          default: "Dados do servidor"
        Parameters: 
          - CMJDBInstanceIdentifier
          - CMJDBName
          - CMJDBInstanceClass
          - CMJAllocatedStorage
      - 
        Label: 
          default: "Dados do usuario"
        Parameters: 
          - CMJMasterUsername
          - CMJMasterUserPassword
          - CMJParametrosUsuarioTimeout
    ParameterLabels: 
      CMJDBInstanceIdentifier: 
        default: "Nome da instancia"      
      CMJDBName: 
        default: "Nome da base de dados"
      CMJDBInstanceClass: 
        default: "Classe da instancia DB"     
      CMJAllocatedStorage: 
        default: "Tamanho do armazenamento"             
      CMJMasterUsername: 
        default: "Nome do usuario"      
      CMJMasterUserPassword: 
        default: "Senha"
      CMJParametrosUsuarioTimeout: 
        default: "Prazo para conexao (time-out)"     
      CMJVpcId: 
        default: "Nome da rede"    
      CMJCidrIpPermitido: 
        default: "IP para acesso publico"    
      CMJEnviromentName: 
        default: "Ambiente (desenvolvimento/testes/producao/treinamento)"    
      CMJCriarParametrosPergunta: 
        default: "Criar parametros?"     
      CMJAcessoPublicoPergunta: 
        default: "Permitir acesso publico?"                                                                        
Resources:
  CMJParametrosServidorNome:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    DependsOn: CMJRDSDBInstance
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/servidor/nome']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value: !GetAtt CMJRDSDBInstance.Endpoint.Address  
  CMJParametrosServidorPorta:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    DependsOn: CMJRDSDBInstance
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/servidor/porta']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value:  3306   
  CMJParametrosUsuarioBanco:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/usuario/banco']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value:  !Ref CMJDBName 
  CMJParametrosUsuarioNome:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/usuario/nome']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value:  !Ref CMJMasterUsername                      
  CMJParametrosUsuarioSenha:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/usuario/senha']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value:  !Ref CMJMasterUserPassword          
  CMJParametrosUsuarioTimeout:
    Type: AWS::SSM::Parameter
    Condition: CMJCriarParametrosCondicao
    Properties: 
      Name:  !Join ['', ['/cmjw/', !Ref CMJEnviromentName ,'/',!Ref CMJDBName,'/usuario/time-out']]
      Tags: 
        Ambiente : !Ref CMJEnviromentName
      Type: String 
      Value:  360000  
  CMJRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de seguranca (Security group) do RDS.
      GroupName: !Join ['', [!Ref CMJDBInstanceIdentifier, SecurityGroup]]
      VpcId: !Ref CMJVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref CMJCidrIpPermitido #exemplo 1111.2222.3333.4444/32 
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  CMJRDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Join ['', [!Ref CMJDBInstanceIdentifier, DBInstance]] #  !Ref CMJDBInstanceIdentifier
      DBName: !Ref CMJDBName
      DBInstanceClass: !Ref CMJDBInstanceClass
      StorageType : 'gp2'
      AllocatedStorage: !Ref CMJAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.28" 
      MasterUsername: !Ref CMJMasterUsername
      MasterUserPassword: !Ref CMJMasterUserPassword
      MonitoringInterval: '0'
      PubliclyAccessible :   !If [CMJAcessoPublicoCondicao, true, false] # 'true'
      VPCSecurityGroups : 
        - !Ref CMJRDSSecurityGroup
      BackupRetentionPeriod: '0'     
Outputs:
  CMJRDSSecurityGroupOutputs:
    Description: Security group
    Value: !Ref CMJRDSSecurityGroup
    Export:
      Name: !Join ['', [!Ref CMJDBInstanceIdentifier, SecurityGroup,'Out']] # CMJRDSSecurityGroupOut 
  CMJRDSDBInstanceOutputs:
    Description: Instancia
    Value: !Ref CMJRDSDBInstance
    Export:
      Name: !Join ['', [!Ref CMJDBInstanceIdentifier, DBInstance,'Out']] # CMJRDSDBInstanceOut 
  CMJRDSDBInstanceEndpointAddressOutputs:
    Description: Endpoint
    Value: !GetAtt CMJRDSDBInstance.Endpoint.Address
    Export:
      Name:  !Join ['', [!Ref CMJDBInstanceIdentifier, DBInstance,'EndpointAddress','Out']] # CMJRDSDBInstanceEndpointAddressOut  
   